name: tesla-ver
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - dash=1.19.0
  - dash-core-components=1.3.1
  - dash-html-components=1.0.1
  - dash-renderer=1.1.2
  - dash-table=4.4.1
  - gunicorn=20.0.4
  - pyarrow=3.0.0
  - numpy=1.19.2
  - redis-py=3.5.3
