name: tesla-ver-test
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.0.1
  - python=3.9.1
  - pip:
    - playwright==1.9.1
    - pytest==6.2.2
    - pytest-base-url==1.4.2
    - pytest-playwright==0.0.12
